# Generated by Django 3.2.4 on 2021-06-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_reg1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='reg2',
        ),
    ]
