# Generated by Django 3.2.4 on 2021-06-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_rename_reg_reg2'),
    ]

    operations = [
        migrations.CreateModel(
            name='crt1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobsname', models.CharField(max_length=100)),
            ],
        ),
    ]
