# Generated by Django 3.2.4 on 2021-06-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_crt1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crt1',
            old_name='jobsname',
            new_name='jobname',
        ),
    ]
