# Generated by Django 3.2.4 on 2021-06-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_rename_jobsname_crt1_jobname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crt1',
            new_name='jobnames',
        ),
        migrations.RenameModel(
            old_name='reg1',
            new_name='Messages',
        ),
        migrations.RenameModel(
            old_name='reg2',
            new_name='Registration',
        ),
    ]
