# Generated by Django 3.2.4 on 2021-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_auto_20210614_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillsname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsname', models.CharField(max_length=100)),
                ('jobcategory', models.CharField(max_length=100)),
            ],
        ),
    ]
