# Generated by Django 3.2.4 on 2021-06-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_skillsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillsname',
            old_name='skillsname',
            new_name='skillname',
        ),
    ]
