# Generated by Django 3.2.4 on 2021-06-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_rename_skillsname_skillsname_skillname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobnames',
            new_name='jobs',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='skillsname',
            new_name='skills',
        ),
    ]
