# Generated by Django 3.2.4 on 2021-06-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_auto_20210616_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
        migrations.RenameModel(
            old_name='skills',
            new_name='skill',
        ),
    ]
