# Generated by Django 3.2.4 on 2021-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_auto_20210616_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='joblocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joblocationname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
