# Generated by Django 3.2.4 on 2021-06-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_joblocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
