# Generated by Django 3.2.4 on 2021-06-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_auto_20210620_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='job_discription',
        ),
    ]
