# Generated by Django 3.2.4 on 2021-06-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0016_candidate_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_onboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_Name', models.CharField(max_length=100)),
                ('jobs', models.CharField(max_length=100)),
                ('Job_locations', models.CharField(max_length=100)),
                ('joining_date', models.DateField(max_length=100)),
                ('accept_last_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
