# Generated by Django 3.2.4 on 2021-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0017_job_onboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.CharField(max_length=100)),
                ('Employee', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField(max_length=100)),
            ],
        ),
    ]
