# Generated by Django 3.2.4 on 2021-06-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0018_interview_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ask_application_for',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='section_visibility',
            field=models.BooleanField(max_length=100, null=True),
        ),
    ]
