# Generated by Django 3.2.4 on 2021-06-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0019_auto_20210624_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ask_application_for',
        ),
        migrations.RemoveField(
            model_name='job',
            name='section_visibility',
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_discription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_requirement',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='meta_title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_positions',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
