# Generated by Django 3.2.4 on 2021-06-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0020_auto_20210624_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
