# Generated by Django 3.2.4 on 2021-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0021_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
